accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path 
from . import views

app_name = 'articles'
urlpatterns = [
  path('', views.index, name='index'),
  path('create/', views.create, name='create'),
  path('<int:pk>/', views.detail, name='detail'),
  path('<int:pk>/movie/', views.movie_detail, name='movie_detail'),
  path('<int:pk>/update/', views.update, name='update'),
  path('<int:pk>/delete/', views.delete, name='delete'),
  path('<int:pk>/comments/', views.comment_create, name='comment_create'),
  path('<int:article_pk>/comments/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
  path('<int:pk>/like/', views.like, name='like'),
]

movieforum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models
from django.conf import settings

# Create your models here.

class Movie(models.Model):
    title = models.CharField(max_length=100)
    poster_path = models.CharField(max_length=150, null = True)
    tmd_id = models.CharField(max_length=50)
    genre = models.CharField(max_length=50, null = True)
    overview = models.TextField()
    release_date = models.CharField(max_length=50)
    backdrop_path = models.CharField(max_length=150, null = True)
    
    
    def __str__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    grade = models.IntegerField()
    image = ProcessedImageField(upload_to='images/', blank=True,
                                processors=[ResizeToFill(1200, 960)],
                                format='JPEG',
                                options={'quality': 80})
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
                            
class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

articles/forms.py
from django import forms
from .models import Article, Comment

GRADE_POINT_CHOICES = (
    ('1', 1),
    ('2', 2),
    ('3', 3),
    ('4', 4),
    ('5', 5),
)

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'content', 'image', 'grade', ]
        widgets = {
            'grade': forms.Select(choices=GRADE_POINT_CHOICES)
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment 
        fields = ['content', ]

articles/views.py
from django.http import JsonResponse
import requests
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_safe
from .models import Article, Comment, Movie
from .forms import ArticleForm, CommentForm
from django.core.paginator import Paginator

# Create your views here.

my_api_key = '801b2f9c7a6d8dce6f3bd7f807c9ffc5'
base_url = 'https://api.themoviedb.org/3/'

@require_safe
def index(request):
    # Article logic
    page = request.GET.get('page', '1')
    articles = Article.objects.order_by('-pk')
    paginator = Paginator(articles, 10)
    page_obj = paginator.get_page(page)

    response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=801b2f9c7a6d8dce6f3bd7f807c9ffc5&language=ko-KR')
    response_dict = response.json().get('results')

    for resData in response_dict:
        tmd_id = resData.get('id')
        
        Movie.objects.get_or_create(
            title = resData.get('title'),
            backdrop_path = resData.get('backdrop_path'),
            poster_path = resData.get('poster_path'),
            overview = resData.get('overview'),
            release_date = resData.get('release_date'),
            genre = resData.get('genres'),
            tmd_id = tmd_id,
            )

    movies = Movie.objects.all().order_by('id')[:4]

    context = {
        'movies' : movies, 
        'articles': articles, 
        'articles_list' : page_obj,
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, request.FILES)
        if article_form.is_valid():
            article = article_form.save(commit=False)
            article.user = request.user 
            article.save()
            messages.success(request, '글 작성이 완료되었습니다.')
            return redirect('articles:index')
    else: 
        article_form = ArticleForm()
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context=context)

def movie_detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    context = {
        'movie' : movie,
    }
    return render(request, 'articles/movie.html', context)

def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    page = request.GET.get('page', '1')
    comments = article.comment_set.all()
    paginator = Paginator(comments, 5)
    page_obj = paginator.get_page(page)
    comment_form = CommentForm()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments' : page_obj
    }
    return render(request, 'articles/detail.html', context)

@login_required
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user == article.user: 
        if request.method == 'POST':
            article_form = ArticleForm(request.POST, request.FILES, instance=article)
            if article_form.is_valid():
                article_form.save()
                messages.success(request, '글이 수정되었습니다.')
                return redirect('articles:detail', article.pk)
        else:
            article_form = ArticleForm(instance=article)
        context = {
            'article_form': article_form
        }
        return render(request, 'articles/form.html', context)
    else:
        messages.warning(request, '작성자만 수정할 수 있습니다.')
        return redirect('articles:detail', article.pk)

@login_required
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect('articles:index')

@login_required
def comment_create(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        context = {
            'content': comment.content,
            'userName': comment.user.username
        }
        return JsonResponse(context)

def comment_delete(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()

    return redirect('articles:detail', article_pk)

    

@login_required
def like(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.user in article.like_users.all(): 
        article.like_users.remove(request.user)
        is_liked = False
    else:
        article.like_users.add(request.user)
        is_liked = True
    context = {'isLiked': is_liked, 'likeCount': article.like_users.count()}
    return JsonResponse(context)

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block section %}
  <div class="d-flex justify-content-center mt-5">
    <div style="width: 30rem; height: 75rem;" class="bg-light rounded-3">
      <div class="p-3">
        <div>
          <div>
            <h2>{{ article.title }}</h2>
            <p class="m-0">평점 :
              {{ article.grade }}/5</p>
            <p class="font-monospace m-0">작성 시간 :
              {{ article.created_at|date:'Y-m-d h:i A'}}
              | 작성자 :
              <a href="{% url 'accounts:detail' article.user.pk %}">{{ article.user }}</a>
            </p>
          </div>
          <div class="text-end mt-3">
            {% if request.user == article.user %}
              <a href="{% url 'articles:update' article.pk %}" class="btn btn-outline-secondary">수정하기</a>
              <a href="{% url 'articles:delete' article.pk %}" class="btn btn-outline-danger">삭제하기</a>
            {% endif %}
          </div>
          <hr>
        </div>
        <div style="height: 400px;">
          <p>{{ article.content }}</p>
          {% if article.image %}
            <img src="{{ article.image.url }}" style="max-width: 300px;">
          {% endif %}
        </div>
        {% if request.user.is_authenticated %}
          {% if request.user in article.like_users.all %}
            <div class=" text-center" ="text-center" ">
              <button class=" btn btn-primary">
                <i id="like-btn" data-article-id="{{ article.pk }}" class="bi bi-heart-fill"></i>
                <span id="like-count">{{ article.like_users.count }}</span>
              </button>
            </div>
          {% else %}
            <div class="text-center">
              <button class="btn btn-primary">
                <i id="like-btn" data-article-id="{{ article.pk }}" class="bi bi-heart"></i>
                <span id="like-count">{{ article.like_users.count }}</span>
              </button>
            </div>
          {% endif %}
        {% endif %}
        <h5 class="mt-4">댓글</h5>
        <hr>
        <div id="comments">
          {% for comment in comments %}
            <p>{{ comment.user.username }}
              |
              {{ comment.content }}
            </p>
            <hr>
          {% endfor %}
        </div>
        <ul class="pagination justify-content-center mt-3">
          {% if comments.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ comments.previous_page_number }}">이전</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
          {% endif %}
          {% for page_number in comments.paginator.page_range %}
            {% if page_number == comments.number %}
              <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
              </li>
            {% endif %}
          {% endfor %}
          {% if comments.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ comments.next_page_number }}">다음</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
          {% endif %}
        </ul>
        {% if request.user.is_authenticated %}
          <div class="py-3 ">
            <form id="comment-form" data-article-id="{{ article.pk }}">
              {% csrf_token %}
              {% bootstrap_form comment_form layout='floating'%}
              <button type="submit" class="btn btn-primary float-end">댓글 작성</button>
            </form>
          </div>
        {% endif %}
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const likeBtn = document.querySelector('#like-btn')
    likeBtn.addEventListener('click', function (event) {
      console.log(event.target.dataset)
      axios({method: 'get', url: `/articles/${event.target.dataset.articleId}/like/`}).then(response => {
        console.log(response)
        console.log(response.data)
        if (response.data.isLiked === true) {
          event
            .target
            .classList
            .add('bi-heart-fill')
          event
            .target
            .classList
            .remove('bi-heart')
        } else {
          event
            .target
            .classList
            .add('bi-heart')
          event
            .target
            .classList
            .remove('bi-heart-fill')
        }
        const likeCount = document.querySelector('#like-count')
        likeCount.innerText = response.data.likeCount
      })
    })
  </script>
  <script>
    const commentForm = document.querySelector('#comment-form')
    const csrftoken = document
      .querySelector('[name=csrfmiddlewaretoken]')
      .value
      commentForm
      .addEventListener('submit', function (event) {
        event.preventDefault();
        axios({
          method: 'post',
          url: `/articles/${event.target.dataset.articleId}/comments/`,
          headers: {
            'X-CSRFToken': csrftoken
          },
          data: new FormData(commentForm)
        }).then(response => {
          console.log(response.data)
          const comments = document.querySelector('#comments')
          const p = document.createElement('p')
          p.innerText = `${response.data.userName} | ${response.data.content}`
          const hr = document.createElement('hr')
          comments.append(p, hr)
          commentForm.reset()
        })
      })
  </script>
{% endblock %}

articles/templates/articles/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block section %}
  <div class="d-flex justify-content-center mt-5">
    <div style="width: 30rem; height: 43rem;" class="bg-light rounded-3">
      <div class="p-3">
        <h2 class="text-center">글 작성</h2>
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form article_form %}
          <button type='submit' class="btn btn-primary float-end">작성</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block css %}
  <style>
    .card {
      margin-bottom: 2rem;
    }
  </style>
{% endblock css %}

{% block section %}
  <div class="my-3">
    <h2 class="fw-bold" style="color: #f9c22e"># 인기 영화</h2>
    <div class="bg-light rounded-4 p-3" style="height: 30rem;">
      <div class="d-flex justify-content-around">
        {% for movie in movies %}
          <div class="text-center">
            <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" class="card-img-top rounded-4" style="max_width: 230px; height: 320px;">
            <a href="{% url 'articles:movie_detail' movie.pk %}">
              <h5 class="py-3 fw-bold">{{ movie.title }}</h5>
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <div>
    <h2 class="fw-bold" style="color: #f9c22e"># 자유 게시판</h2>
    <div class="bg-light rounded-4 p-3" style="height: 30rem;">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">작성자</th>
            <th scope="col">글 제목</th>
            <th scope="col">작성 시간</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles_list %}
            <tr>
              <th>
                <a href="{% url 'articles:detail' article.pk %}">{{ article.user }}</a>
              </th>
              <td>{{ article.title }}</td>
              <td>{{ article.created_at|date:'Y-m-d h:i A' }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <ul class="pagination justify-content-center mt-3">
      {% if articles_list.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ articles_list.previous_page_number }}">이전</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
      {% endif %}
      {% for page_number in articles_list.paginator.page_range %}
        {% if page_number == articles_list.number %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if articles_list.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ articles_list.next_page_number }}">다음</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
      {% endif %}
    </ul>
  </div>
{% endblock %}

articles/templates/articles/movie.html
{% extends 'base.html' %}

{% block section %}
  <div class="d-flex flex-column mt-5 bg-light rounded-3" style="height: 40rem;">
    <div class="p-4 d-flex justify-content-between">
      <div>
        <h1>{{ movie.title }}</h1>
        <p>({{ movie.release_date }})</p>
        <hr>
        <p>{{ movie.overview }}</p>
      </div>
      <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" class="rounded-5 p-4" style="width: 300px; height: 420px;">
    </div>
    <hr class="border border-danger border-2 opacity-50">
  </div>
{% endblock %}